# SK

test:
  container_name: ft-test-log-php-test
  image: ziridis/ft-test-log-php-test
  environment: 
   - API_SERVER=192.168.0.145
  ports:
   - 80:80
  volumes:
     - /var/www/html/
api:
  container_name: ft-test-log-php
  image: ziridis/ft-test-log-php
  environment: 
   - SQL_SERVER=192.168.0.145
  ports:
   - 8080:80
  volumes:
     - /var/www/html/
db:
  image: mysql:5.7
  container_name: mysql
  volumes:
   - /var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: fttestlogphp
   MYSQL_DATABASE: fttestlogphp
   MYSQL_USER: fttestlogphp
   MYSQL_PASSWORD: fttestlogphp
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_ARBITRARY=1
  restart: always
  ports:
   - 8081:80
  volumes:
   - /sessions
