# Composition of the containers needed

db:
  image: mysql:5.7
  container_name: mysql
  volumes:
   - /var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: ftdevenv
   MYSQL_DATABASE: ft-test-log
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_ARBITRARY=1
  restart: always
  ports:
   - 8081:80
  volumes:
   - /sessions